### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by kenjdavidson** [kenjdavidson/react-native-bluetooth-classic#108]
Docs:
Update github action with original Gatsby publish
- PUSH/PULL_MERGE should release
- PULL_REQUEST should build only

Library:
Update actions with release on merge 
- Implement the conventional commits (without semantic versioning due to react native version)
- `npm run release` should be used after build to maintain correct versioning

**Comment by kenjdavidson** [comment]
Push should be updated to release, I would think.  But I'm unsure when release is run (tags? or actual release)

```
# Documentation Build & Publish
name: documentation

# Fired on push (master) and pull_request (all)
on:
  push:
    branches:
      - master
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner on which this job will run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.16.3']

    # Steps represent a sequence of tasks that will be executed as part of the job
    # - Checkout gatsby branch
    # - Update authentication for Github Package Registry @kenjdavidson/base16-scss
    # - Build gh-pages using action
    # - Skip publish if this is anything other than a push (master)
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc
      - uses: enriikke/gatsby-gh-pages-action@v2.1.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          working-dir: ./docs
          gatsby-args: --prefix-paths
          skip-publish: ${{ github.event != 'push' }}
```
